server:  port: 9001
spring:  h2:    console:      enabled: true  sql:    init:      platform: h2  datasource:    url: jdbc:h2:mem:ankur  jpa:    show-sql: true  application:    name: DEPARTMENT-SERVICE        